# Generated by Codex on 2026-06-23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["unit_price"], name="products_pr_unit_pr_e8ae58_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["quantity"], name="products_pr_quantity_1552e0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="products_pr_created_a05ba4_idx"),
        ),
    ]
